name: autodev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - cudatoolkit=11.7
  - cudnn=8.9.2.26
  - pip
  - pip:
    - tiktoken==0.4.0
    - flask==2.3.2
    - chromadb==0.3.21
    - transformers==4.30.2
    - langchain==0.0.171
    - peft==0.3.0
    - accelerate==0.20.3
    - xformers==0.0.19
    - optimum[onnxruntime-gpu]==1.9.0
    - jupyter
    - seaborn==0.12.2
    - mlflow==2.4.2
    - gputil==1.4.0
